create_profile:
  name: "Create plant profile"
  description: "Create a new plant profile stored locally."
  fields:
    profile_id:
      required: true
      example: "avocado_tree_1"
      selector: { text: {} }
    name:
      required: true
      example: "Avocado Tree"
      selector: { text: {} }
    template:
      required: false
      example: "Persea americana"
      selector: { text: {} }
    targets:
      required: false
      description: "Manual targets to override template (temperature/humidity/light/etc)."
      selector: { object: {} }

link_sensor:
  name: "Link sensor to profile"
  description: "Attach an HA sensor entity to a profile for a specific role."
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    entity_id:
      required: true
      selector: { entity: { domain: sensor } }
    role:
      required: true
      description: "temperature | humidity | soil_moisture | illuminance | co2 | ph"
      selector: { select: { options: ["temperature","humidity","soil_moisture","illuminance","co2","ph"] } }

duplicate_profile:
  name: "Duplicate a profile"
  fields:
    from_profile_id:
      required: true
      selector: { text: {} }
    new_profile_id:
      required: true
      selector: { text: {} }
    new_name:
      required: true
      selector: { text: {} }

reset_dli:
  name: "Reset DLI accumulator"
  description: "Resets the Daily Light Integral accumulator for the given profile."
  fields:
    profile_id:
      required: true
      selector: { text: {} }

export_profile:
  name: "Export profile JSON"
  fields:
    profile_id:
      required: true
      selector: { text: {} }

import_profiles:
  name: "Import profile JSON(s)"
  description: "Accepts a list of profile docs (e.g., from Developer Tools → Services) and merges into local storage."
  fields:
    profiles:
      required: true
      selector: { object: {} }

refresh:
  name: "Refresh computations"
  description: "Triggers a data refresh (coordinator update) for all profiles."

record_run_event:
  name: "Record cultivation run"
  description: "Append a run lifecycle event to the profile history."
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    run_id:
      required: true
      selector: { text: {} }
    started_at:
      required: true
      selector: { datetime: {} }
    ended_at:
      required: false
      selector: { datetime: {} }
    environment:
      required: false
      description: "Additional environment metadata captured during the run."
      selector: { object: {} }
    metadata:
      required: false
      description: "Arbitrary metadata describing the run."
      selector: { object: {} }
    targets_met:
      required: false
      description: "Number of target checks that were within range during the run."
      selector: { number: { min: 0 } }
    targets_total:
      required: false
      description: "Total target checks evaluated for the run to derive success rate weighting."
      selector: { number: { min: 0 } }
    success_rate:
      required: false
      description: "Overall success rate for the run (percentage or decimal between 0 and 1)."
      selector: { number: { min: 0, max: 100 } }
    stress_events:
      required: false
      description: "Count of stress or alert events observed during the run."
      selector: { number: { min: 0 } }

record_harvest_event:
  name: "Record harvest event"
  description: "Log a harvest result and recompute yield statistics."
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    harvest_id:
      required: true
      selector: { text: {} }
    harvested_at:
      required: true
      selector: { datetime: {} }
    yield_grams:
      required: true
      selector: { number: { min: 0 } }
    area_m2:
      required: false
      selector: { number: { min: 0 } }
    run_id:
      required: false
      selector: { text: {} }
    metadata:
      required: false
      description: "Additional harvest metadata such as cultivar phenotype notes."
      selector: { object: {} }

record_nutrient_event:
  name: "Record nutrient application"
  description: "Log a nutrient or fertilizer feeding event for the profile and update nutrient metrics."
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    event_id:
      required: true
      selector: { text: {} }
    applied_at:
      required: true
      selector: { datetime: {} }
    product_id:
      required: false
      selector: { text: {} }
    product_name:
      required: false
      selector: { text: {} }
    product_category:
      required: false
      selector: { text: {} }
    species_id:
      required: false
      selector: { text: {} }
    run_id:
      required: false
      selector: { text: {} }
    solution_volume_liters:
      required: false
      selector: { number: { min: 0 } }
    concentration_ppm:
      required: false
      selector: { number: { min: 0 } }
    ec_ms:
      required: false
      selector: { number: { min: 0 } }
    ph:
      required: false
      selector: { number: { min: 0, max: 14 } }
    source:
      required: false
      selector: { text: {} }
    additives:
      required: false
      description: "Optional list of additive notes (e.g. supplements mixed into the solution)."
      selector: { object: {} }
    metadata:
      required: false
      description: "Additional metadata for the feeding (notes, operator, etc.)."
      selector: { object: {} }

record_cultivation_event:
  name: "Record cultivation event"
  description: "Log a cultivation milestone (e.g. pruning, transplant, inspection) and update event statistics."
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    event_id:
      required: true
      selector: { text: {} }
    occurred_at:
      required: true
      selector: { datetime: {} }
    event_type:
      required: true
      description: "Event category such as pruning, inspection, transplant, etc."
      selector: { text: {} }
    species_id:
      required: false
      selector: { text: {} }
    run_id:
      required: false
      selector: { text: {} }
    title:
      required: false
      selector: { text: {} }
    notes:
      required: false
      selector: { text: {} }
    metric_value:
      required: false
      description: "Optional numeric measurement captured during the event (e.g. canopy height)."
      selector: { number: {} }
    metric_unit:
      required: false
      selector: { text: {} }
    actor:
      required: false
      description: "Who performed the event (e.g. technician name)."
      selector: { text: {} }
    location:
      required: false
      selector: { text: {} }
    tags:
      required: false
      description: "List of tags to aid filtering (e.g. maintenance, pest)."
      selector: { object: {} }
    metadata:
      required: false
      description: "Additional structured metadata for the event."
      selector: { object: {} }

profile_provenance:
  name: "Inspect target provenance"
  description: "Return provenance details for all resolved targets in a profile."
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    include_overlay:
      required: false
      default: false
      description: "Include overlay/parent metadata for inherited targets."
      selector: { boolean: {} }
    include_extras:
      required: false
      default: false
      description: "Include raw extras payload captured during resolution."
      selector: { boolean: {} }
    include_citations:
      required: false
      default: false
      description: "Include citation lists for each resolved target."
      selector: { boolean: {} }

profile_runs:
  name: "Summarise grow runs"
  description: "Return lifecycle and harvest summaries for a profile's runs."
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    limit:
      required: false
      description: "Maximum number of runs to include (most recent first)."
      selector: { number: { min: 1, max: 25 } }

cloud_login:
  name: "Cloud login"
  description: "Authenticate with the Horticulture Assistant cloud and store tokens."
  fields:
    base_url:
      required: false
      description: "Override the cloud base URL (defaults to the configured value)."
      selector: { text: {} }
    email:
      required: true
      selector: { text: {} }
    password:
      required: true
      selector: { text: { type: password } }

cloud_logout:
  name: "Cloud logout"
  description: "Disable cloud sync and clear stored tokens."

cloud_refresh_token:
  name: "Refresh cloud token"
  description: "Refresh the stored access token using the configured refresh token."
  fields:
    base_url:
      required: false
      description: "Override the cloud base URL used for the refresh request."
      selector: { text: {} }

cloud_select_org:
  name: "Select cloud organization"
  description: "Set the active cloud organization for subsequent sync operations."
  fields:
    organization_id:
      required: false
      description: "Organization identifier to activate."
      selector: { text: {} }
    organization_name:
      required: false
      description: "Organization name to match when the identifier is unknown."
      selector: { text: {} }
    role:
      required: false
      description: "Optional role override for the active organization context."
      selector: { text: {} }
