refresh:
  name: Refresh
  description: Refresh all Horticulture Assistant coordinators.

recompute:
  name: Recompute
  description: Recompute derived metrics for a profile (or all if omitted).
  fields:
    profile_id:
      required: false
      selector: { text: {} }

reset_dli:
  name: Reset DLI
  description: Clear the accumulated daily light integral for a profile or all profiles.
  fields:
    profile_id:
      required: false
      selector: { text: {} }

refresh_species:
  name: Refresh Species
  description: Refresh species data for a profile.
  fields:
    profile_id:
      required: true
      selector: { text: {} }

create_profile:
  name: Create Profile
  description: Create a new plant profile.
  fields:
    name:
      description: Friendly name for the profile.
      example: Basil
      required: true
      selector: { text: {} }

duplicate_profile:
  name: Duplicate Profile
  description: Copy an existing profile to a new name.
  fields:
    source_profile_id:
      description: ID of the source profile.
      example: basil
      required: true
      selector: { text: {} }
    new_name:
      description: Name for the duplicated profile.
      example: Mint Clone
      required: true
      selector: { text: {} }

delete_profile:
  name: Delete Profile
  fields:
    profile_id:
      required: true
      selector: { text: {} }

update_sensors:
  name: Update Sensors
  description: Link sensor entities to a profile.
  fields:
    profile_id:
      description: Profile identifier.
      required: true
      selector: { text: {} }
    temperature:
      description: Temperature sensor entity.
      selector: { entity: { domain: sensor } }
    humidity:
      description: Humidity sensor entity.
      selector: { entity: { domain: sensor } }
    illuminance:
      description: Illuminance sensor entity.
      selector: { entity: { domain: sensor } }
    moisture:
      description: Moisture sensor entity.
      selector: { entity: { domain: sensor } }

replace_sensor:
  name: Replace Sensor
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    measurement:
      required: true
      selector:
        select:
          options: [temperature, humidity, illuminance, moisture]
    entity_id:
      required: true
      selector: { entity: { domain: sensor } }

apply_irrigation_plan:
  name: Apply Irrigation Plan
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    provider:
      default: auto
      selector:
        select:
          options: [auto, irrigation_unlimited, opensprinkler]
    zone:
      required: false
      selector: { text: {} }

export_profile:
  name: Export Profile
  description: Export a profile to a file.
  fields:
    profile_id:
      description: Profile identifier.
      required: true
      selector: { text: {} }
    path:
      description: Filesystem path to write.
      required: true
      selector: { text: {} }

export_profiles:
  name: Export Profiles
  description: Export all profiles to a file.
  fields:
    path:
      required: true
      selector: { text: {} }

import_profiles:
  name: Import Profiles
  description: Import profiles from a file.
  fields:
    path:
      description: Path to a profile export file.
      required: true
      selector: { text: {} }
