refresh:
  name: Refresh
  description: Refresh all Horticulture Assistant coordinators.

recompute:
  name: Recompute
  description: Recompute derived metrics for a profile (or all if omitted).
  fields:
    profile_id:
      required: false
      selector: { text: {} }

reset_dli:
  name: Reset DLI
  description: Clear the accumulated daily light integral for a profile or all profiles.
  fields:
    profile_id:
      required: false
      selector: { text: {} }

refresh_species:
  name: Refresh Species
  description: Refresh species data for a profile.
  fields:
    profile_id:
      required: true
      selector: { text: {} }

create_profile:
  name: Create Profile
  fields:
    name:
      required: true
      selector: { text: {} }

duplicate_profile:
  name: Duplicate Profile
  fields:
    source_profile_id:
      required: true
      selector: { text: {} }
    new_name:
      required: true
      selector: { text: {} }

delete_profile:
  name: Delete Profile
  fields:
    profile_id:
      required: true
      selector: { text: {} }

link_sensors:
  name: Link Sensors
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    temperature:
      selector: { entity: { domain: sensor } }
    humidity:
      selector: { entity: { domain: sensor } }
    illuminance:
      selector: { entity: { domain: sensor } }
    moisture:
      selector: { entity: { domain: sensor } }

replace_sensor:
  name: Replace Sensor
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    measurement:
      required: true
      selector:
        select:
          options: [temperature, humidity, illuminance, moisture]
    entity_id:
      required: true
      selector: { entity: { domain: sensor } }

apply_irrigation_plan:
  name: Apply Irrigation Plan
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    provider:
      default: auto
      selector:
        select:
          options: [auto, irrigation_unlimited, opensprinkler]
    zone:
      required: false
      selector: { text: {} }

export_profile:
  name: Export Profile
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    path:
      required: true
      selector: { text: {} }

export_profiles:
  name: Export Profiles
  description: Export all profiles to a file.
  fields:
    path:
      required: true
      selector: { text: {} }

import_profiles:
  name: Import Profiles
  fields:
    path:
      required: true
      selector: { text: {} }
