create_profile:
  name: Create plant profile
  description: Create a new plant profile managed by Horticulture Assistant.
  fields:
    name:
      required: true
      selector:
        text:

duplicate_profile:
  name: Duplicate plant profile
  description: Clone an existing plant profile under a new name.
  fields:
    source_profile_id:
      required: true
      selector:
        text:
    new_name:
      required: true
      selector:
        text:

delete_profile:
  name: Delete plant profile
  description: Remove a plant profile, its stored data, and any associated sensors.
  fields:
    profile_id:
      required: true
      selector:
        text:

link_sensors:
  name: Link sensors to profile
  description: Attach sensor entity IDs to a plant profile.
  fields:
    profile_id:
      required: true
      selector:
        text:
    temperature:
      selector:
        entity:
          domain: sensor
    humidity:
      selector:
        entity:
          domain: sensor
    illuminance:
      selector:
        entity:
          domain: sensor
    moisture:
      selector:
        entity:
          domain: sensor

update_sensors:
  name: Update plant sensors
  description: Attach or replace sensor entity IDs for a plant profile.
  fields:
    plant_id:
      required: true
      example: citrus_backyard_spring2025
      selector:
        text:
    sensors:
      required: true
      example:
        moisture_sensors: [sensor.soil_moist_1, sensor.soil_moist_2]
        temperature_sensors: [sensor.greenhouse_temp]
        ec_sensors: [sensor.substrate_ec]
      selector:
        object:

recalculate_targets:
  name: Recalculate nutrient/environment targets
  fields:
    plant_id:
      required: true
      selector:
        text:

run_recommendation:
  name: Run recommendation
  fields:
    plant_id:
      required: true
      selector:
        text:
    approve:
      required: false
      default: false
      selector:
        boolean:

refresh:
  name: Manual refresh
  description: Trigger both local and AI coordinators to refresh now.

recompute:
  name: Recompute Metrics
  description: Force coordinator to recompute metrics for all profiles or one profile.
  fields:
    profile_id:
      required: false
      selector:
        text:

replace_sensor:
  name: Replace a mapped sensor
  description: Swap the source sensor feeding a plant profile.
  fields:
    profile_id:
      required: true
      selector:
        text:
    meter_entity:
      required: true
      selector:
        entity:
          domain: sensor
    new_sensor:
      required: true
      selector:
        entity:
          domain: sensor

apply_irrigation_plan:
  name: Apply irrigation plan
  description: Use Smart Irrigation recommendation and run via Irrigation Unlimited or OpenSprinkler.
  fields:
    profile_id:
      required: true
      selector:
        text:
    provider:
      required: false
      default: auto
      selector:
        select:
          options:
            - auto
            - irrigation_unlimited
            - opensprinkler
    zone:
      required: false
      selector:
        text:

resolve_profile:
  name: Resolve profile preferences
  description: Resolve all per-variable sources into numeric thresholds for a profile.
  fields:
    profile_id:
      required: true
      selector:
        text:

resolve_all:
  name: Resolve all profiles
  description: Resolve all profiles that have needs_resolution=true or expired AI TTL.

generate_profile:
  name: Generate profile
  description: Populate all variables for a profile from a single source.
  fields:
    profile_id:
      required: true
      selector:
        text:
    mode:
      required: true
      selector:
        select:
          options:
            - clone
            - opb
            - ai
    source_profile_id:
      required: false
      selector:
        text:

export_profiles:
  name: Export profiles
  description: Write all stored profiles to a JSON file on disk.
  fields:
    path:
      required: true
      selector:
        text:
export_profile:
  name: Export profile
  description: Write a single profile to a JSON file on disk.
  fields:
    profile_id:
      required: true
      selector:
        text:
    path:
      required: true
      selector:
        text:
import_profiles:
  name: Import profiles
  description: Load profiles from a JSON file and merge into storage.
  fields:
    path:
      required: true
      selector:
        text:

clear_caches:
  name: Clear caches
  description: Remove cached AI recommendations and OpenPlantbook lookups.

start_calibration:
  name: Start Lux→PPFD calibration
  description: Begin a calibration session for a Lux sensor against a PPFD reference.
  fields:
    lux_entity_id: { required: true, selector: { entity: { domain: sensor, device_class: illuminance } } }
    ppfd_entity_id: { required: false, selector: { entity: { domain: sensor } } }
    model:
      required: false
      default: linear
      selector: { select: { options: ["linear","quadratic","power"] } }
    averaging_seconds:
      required: false
      default: 3
      selector: { number: { min: 1, max: 30, step: 1, mode: box } }
    notes: { required: false, selector: { text: {} } }

add_calibration_point:
  name: Add calibration point
  description: Capture a Lux/PPFD pair for the active session.
  fields:
    session_id: { required: true, selector: { text: {} } }
    ppfd_value:
      required: false
      description: "If no PPFD entity was chosen, enter the current PPFD reading from your PAR sensor."
      selector: { number: { min: 0, max: 3000, step: 1, mode: box } }

finish_calibration:
  name: Finish calibration
  description: Finalize the curve fit, store coefficients, and apply to derived PPFD/DLI.
  fields:
    session_id: { required: true, selector: { text: {} } }

abort_calibration:
  name: Abort calibration
  description: Cancel a running calibration session.
  fields:
    session_id: { required: true, selector: { text: {} } }
