create_profile:
  name: "Create plant profile"
  description: "Create a new plant profile stored locally."
  fields:
    profile_id:
      required: true
      example: "avocado_tree_1"
      selector: { text: {} }
    name:
      required: true
      example: "Avocado Tree"
      selector: { text: {} }
    template:
      required: false
      example: "Persea americana"
      selector: { text: {} }
    targets:
      required: false
      description: "Manual targets to override template (temperature/humidity/light/etc)."
      selector: { object: {} }

link_sensor:
  name: "Link sensor to profile"
  description: "Attach an HA sensor entity to a profile for a specific role."
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    entity_id:
      required: true
      selector: { entity: { domain: sensor } }
    role:
      required: true
      description: "temperature | humidity | soil_moisture | illuminance | co2 | ph"
      selector: { select: { options: ["temperature","humidity","soil_moisture","illuminance","co2","ph"] } }

duplicate_profile:
  name: "Duplicate a profile"
  fields:
    from_profile_id:
      required: true
      selector: { text: {} }
    new_profile_id:
      required: true
      selector: { text: {} }
    new_name:
      required: true
      selector: { text: {} }

reset_dli:
  name: "Reset DLI accumulator"
  description: "Resets the Daily Light Integral accumulator for the given profile."
  fields:
    profile_id:
      required: true
      selector: { text: {} }

export_profile:
  name: "Export profile JSON"
  fields:
    profile_id:
      required: true
      selector: { text: {} }

import_profiles:
  name: "Import profile JSON(s)"
  description: "Accepts a list of profile docs (e.g., from Developer Tools → Services) and merges into local storage."
  fields:
    profiles:
      required: true
      selector: { object: {} }

refresh:
  name: "Refresh computations"
  description: "Triggers a data refresh (coordinator update) for all profiles."

record_run_event:
  name: "Record cultivation run"
  description: "Append a run lifecycle event to the profile history."
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    run_id:
      required: true
      selector: { text: {} }
    started_at:
      required: true
      selector: { datetime: {} }
    ended_at:
      required: false
      selector: { datetime: {} }
    environment:
      required: false
      description: "Additional environment metadata captured during the run."
      selector: { object: {} }
    metadata:
      required: false
      description: "Arbitrary metadata describing the run."
      selector: { object: {} }
    targets_met:
      required: false
      description: "Number of target checks that were within range during the run."
      selector: { number: { min: 0 } }
    targets_total:
      required: false
      description: "Total target checks evaluated for the run to derive success rate weighting."
      selector: { number: { min: 0 } }
    success_rate:
      required: false
      description: "Overall success rate for the run (percentage or decimal between 0 and 1)."
      selector: { number: { min: 0, max: 100 } }
    stress_events:
      required: false
      description: "Count of stress or alert events observed during the run."
      selector: { number: { min: 0 } }

record_harvest_event:
  name: "Record harvest event"
  description: "Log a harvest result and recompute yield statistics."
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    harvest_id:
      required: true
      selector: { text: {} }
    harvested_at:
      required: true
      selector: { datetime: {} }
    yield_grams:
      required: true
      selector: { number: { min: 0 } }
    area_m2:
      required: false
      selector: { number: { min: 0 } }
    run_id:
      required: false
      selector: { text: {} }
    metadata:
      required: false
      description: "Additional harvest metadata such as cultivar phenotype notes."
      selector: { object: {} }

profile_provenance:
  name: "Inspect target provenance"
  description: "Return provenance details for all resolved targets in a profile."
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    include_overlay:
      required: false
      default: false
      description: "Include overlay/parent metadata for inherited targets."
      selector: { boolean: {} }
    include_extras:
      required: false
      default: false
      description: "Include raw extras payload captured during resolution."
      selector: { boolean: {} }
    include_citations:
      required: false
      default: false
      description: "Include citation lists for each resolved target."
      selector: { boolean: {} }
