create_profile:
  name: "Create plant profile"
  description: "Create a new plant profile stored locally."
  fields:
    profile_id:
      required: true
      example: "avocado_tree_1"
      selector: { text: {} }
    name:
      required: true
      example: "Avocado Tree"
      selector: { text: {} }
    template:
      required: false
      example: "Persea americana"
      selector: { text: {} }
    targets:
      required: false
      description: "Manual targets to override template (temperature/humidity/light/etc)."
      selector: { object: {} }

link_sensor:
  name: "Link sensor to profile"
  description: "Attach an HA sensor entity to a profile for a specific role."
  fields:
    profile_id:
      required: true
      selector: { text: {} }
    entity_id:
      required: true
      selector: { entity: { domain: sensor } }
    role:
      required: true
      description: "temperature | humidity | soil_moisture | illuminance | co2 | ph"
      selector: { select: { options: ["temperature","humidity","soil_moisture","illuminance","co2","ph"] } }

duplicate_profile:
  name: "Duplicate a profile"
  fields:
    from_profile_id:
      required: true
      selector: { text: {} }
    new_profile_id:
      required: true
      selector: { text: {} }
    new_name:
      required: true
      selector: { text: {} }

reset_dli:
  name: "Reset DLI accumulator"
  description: "Resets the Daily Light Integral accumulator for the given profile."
  fields:
    profile_id:
      required: true
      selector: { text: {} }

export_profile:
  name: "Export profile JSON"
  fields:
    profile_id:
      required: true
      selector: { text: {} }

import_profiles:
  name: "Import profile JSON(s)"
  description: "Accepts a list of profile docs (e.g., from Developer Tools → Services) and merges into local storage."
  fields:
    profiles:
      required: true
      selector: { object: {} }

refresh:
  name: "Refresh computations"
  description: "Triggers a data refresh (coordinator update) for all profiles."
