line-length = 120
target-version = "py312"
extend-exclude = [
  "custom_components/horticulture_assistant/data/**",
  "plant_engine/**",
]

[lint]
select = ["E", "F", "W", "UP", "I"]
ignore = ["D"]

[lint.isort]
known-first-party = ["custom_components.horticulture_assistant"]
