"""Plant engine package utilities."""

from .utils import load_json, save_json
from .datasets import list_datasets, get_dataset_description, search_datasets
from .environment_manager import (
    get_environmental_targets,
    recommend_environment_adjustments,
    optimize_environment,
    calculate_environment_metrics,
    calculate_absolute_humidity,
    get_target_dli,
    get_target_vpd,
    get_target_photoperiod,
    photoperiod_for_target_dli,
    calculate_dli,
    calculate_dli_series,
    humidity_for_target_vpd,
    get_target_co2,
    calculate_co2_injection,
    recommend_co2_injection,
    get_co2_price,
    get_co2_efficiency,
    estimate_co2_cost,
    recommend_co2_injection_with_cost,
    calculate_co2_injection_series,
    calculate_co2_cost_series,
    CO2_MG_PER_M3_PER_PPM,
    get_humidity_action,
    recommend_humidity_action,
    recommend_photoperiod,
    EnvironmentMetrics,
    EnvironmentOptimization,
    StressFlags,
    evaluate_wind_stress,
    evaluate_stress_conditions,
    list_supported_plants as list_environment_plants,
)
from .pest_manager import (
    get_pest_guidelines,
    recommend_treatments as recommend_pest_treatments,
    list_supported_plants as list_pest_plants,
    get_pest_prevention,
    recommend_prevention as recommend_pest_prevention,
)
from .pest_monitor import (
    get_pest_thresholds,
    assess_pest_pressure,
    recommend_threshold_actions,
)
from .pesticide_manager import (
    get_withdrawal_days,
    earliest_harvest_date,
    adjust_harvest_date,
    get_reentry_hours,
    earliest_reentry_time,
    calculate_reentry_window,
)
from .disease_monitor import (
    get_disease_thresholds,
    assess_disease_pressure,
    classify_disease_severity,
    recommend_threshold_actions as recommend_disease_threshold_actions,
    estimate_disease_risk,
    generate_disease_report,
)
from .integrated_monitor import generate_integrated_monitoring_schedule
from .disease_manager import (
    get_disease_guidelines,
    recommend_treatments as recommend_disease_treatments,
    list_supported_plants as list_disease_plants,
    get_disease_prevention,
    recommend_prevention as recommend_disease_prevention,
    get_disease_resistance,
)
from .fertigation import (
    recommend_fertigation_schedule,
    recommend_correction_schedule,
    get_fertilizer_purity,
    recommend_rootzone_fertigation,
    optimize_fertigation_schedule,
    recommend_nutrient_mix_with_cost_breakdown,
    generate_fertigation_plan,
    calculate_mix_nutrients,
    estimate_stage_cost,
    estimate_cycle_cost,
    generate_cycle_fertigation_plan,
    generate_cycle_fertigation_plan_with_cost,
    recommend_loss_compensated_mix,
    recommend_stock_solution_injection,
    get_foliar_spray_volume,
    estimate_spray_solution_volume,
)
from .rootzone_model import (
    estimate_rootzone_depth,
    estimate_water_capacity,
    get_soil_parameters,
    get_infiltration_rate,
    estimate_infiltration_time,
    RootZone,
)
from .soil_manager import (
    list_supported_plants as list_soil_plants,
    get_soil_targets,
    calculate_soil_deficiencies,
    calculate_soil_surplus,
    score_soil_nutrients,
)
from .irrigation_manager import (
    recommend_irrigation_volume,
    recommend_irrigation_interval,
    list_supported_plants as list_irrigation_plants,
    get_daily_irrigation_target,
    generate_irrigation_schedule,
    generate_cycle_irrigation_plan,
)
from .nutrient_manager import (
    calculate_deficiencies,
    calculate_all_surplus,
    list_supported_plants as list_nutrient_plants,
)
from .micro_manager import (
    list_supported_plants as list_micro_plants,
    get_recommended_levels as get_micro_levels,
    calculate_deficiencies as calculate_micro_deficiencies,
    calculate_surplus as calculate_micro_surplus,
)
from .silicon_manager import (
    list_supported_plants as list_silicon_plants,
    get_recommended_levels as get_silicon_levels,
    calculate_deficiencies as calculate_silicon_deficiencies,
    calculate_surplus as calculate_silicon_surplus,
)
from .bioinoculant_manager import (
    list_supported_plants as list_bio_plants,
    get_recommended_inoculants,
)
from .companion_manager import (
    list_supported_plants as list_companion_plants,
    get_companion_info,
    recommend_companions,
    recommend_antagonists,
)
from .rotation_manager import (
    list_supported_plants as list_rotation_plants,
    get_rotation_info,
    recommended_rotation_years,
)
from .growth_stage import (
    get_stage_info,
    list_growth_stages,
    days_until_next_stage,
)
from .stage_tasks import (
    list_supported_plants as list_task_plants,
    get_stage_tasks,
    generate_task_schedule,
)
from .harvest_planner import build_stage_schedule
from .guidelines import get_guideline_summary
from .report import DailyReport
from .engine import load_profile
from .health_report import generate_health_report
from .deficiency_manager import (
    get_deficiency_treatment,
    recommend_deficiency_treatments,
    diagnose_deficiency_actions,
)
from .surplus_manager import (
    list_known_nutrients as list_surplus_nutrients,
    get_surplus_action,
    recommend_surplus_actions,
)
from .nutrient_interactions import (
    list_interactions,
    get_interaction_info,
    get_max_ratio,
    get_interaction_message,
    check_imbalances,
    get_balance_action,
    recommend_balance_actions,
    analyze_interactions,
)
from .yield_manager import (
    HarvestRecord,
    load_yield_history,
    record_harvest,
    get_total_yield,
    get_total_nutrient_removal,
)
from .yield_prediction import (
    list_supported_plants as list_yield_plants,
    get_estimated_yield,
    estimate_remaining_yield,
)
from .constants import get_stage_multiplier, STAGE_MULTIPLIERS, DEFAULT_ENV
from .pruning_manager import (
    list_supported_plants as list_pruning_plants,
    list_stages as list_pruning_stages,
    get_pruning_instructions,
)
from .nutrient_analysis import analyze_nutrient_profile
from .nutrient_leaching import (
    list_known_nutrients as list_leaching_nutrients,
    get_leaching_rate,
    estimate_leaching_loss,
    compensate_for_leaching,
)
from .nutrient_volatilization import (
    list_known_nutrients as list_volatilization_nutrients,
    get_volatilization_rate,
    estimate_volatilization_loss,
    compensate_for_volatilization,
)
from .nutrient_recovery import (
    list_known_nutrients as list_recovery_nutrients,
    get_recovery_factor,
    estimate_recovered_amounts,
    adjust_for_recovery,
)
from .water_quality import (
    list_analytes as list_water_analytes,
    get_threshold as get_water_threshold,
    interpret_water_profile,
)
from .ec_manager import (
    list_supported_plants as list_ec_plants,
    get_ec_range,
    classify_ec_level,
    recommend_ec_adjustment,
)
from .water_usage import (
    list_supported_plants as list_water_use_plants,
    get_daily_use as get_daily_water_use,
    estimate_stage_total_use,
    estimate_cycle_total_use,
)
from .water_costs import get_water_cost_rate, estimate_water_cost
from .toxicity_manager import (
    list_supported_plants as list_toxicity_plants,
    get_toxicity_thresholds,
    check_toxicities,
)
from .nutrient_status import classify_nutrient_status
from .ph_manager import (
    list_supported_plants as list_ph_plants,
    get_ph_range,
    recommend_ph_adjustment,
    estimate_ph_adjustment_volume,
)
from .light_spectrum import (
    list_supported_plants as list_spectrum_plants,
    get_spectrum as get_light_spectrum,
    get_red_blue_ratio,
)
from .thermal_time import (
    calculate_gdd,
    list_supported_plants as list_gdd_plants,
    get_stage_gdd_requirement,
    predict_stage_completion,
    accumulate_gdd_series,
)
from .nutrient_budget import (
    list_supported_plants as list_budget_plants,
    get_removal_rates,
    estimate_total_removal,
    estimate_required_nutrients,
)
from .compute_transpiration import TranspirationMetrics
from .nutrient_efficiency import calculate_nue, calculate_nue_for_nutrient
from .nutrient_schedule import generate_daily_uptake_plan

# Run functions should be imported explicitly to avoid heavy imports at package
# initialization time.
__all__ = [
    "load_json",
    "save_json",
    "list_datasets",
    "get_dataset_description",
    "search_datasets",
    "get_environmental_targets",
    "recommend_environment_adjustments",
    "optimize_environment",
    "calculate_environment_metrics",
    "calculate_absolute_humidity",
    "get_target_dli",
    "get_target_vpd",
    "get_target_photoperiod",
    "photoperiod_for_target_dli",
    "calculate_dli",
    "calculate_dli_series",
    "get_target_co2",
    "calculate_co2_injection",
    "recommend_co2_injection",
    "get_co2_price",
    "get_co2_efficiency",
    "estimate_co2_cost",
    "recommend_co2_injection_with_cost",
    "calculate_co2_injection_series",
    "calculate_co2_cost_series",
    "CO2_MG_PER_M3_PER_PPM",
    "humidity_for_target_vpd",
    "get_humidity_action",
    "recommend_humidity_action",
    "recommend_photoperiod",
    "EnvironmentMetrics",
    "EnvironmentOptimization",
    "StressFlags",
    "evaluate_wind_stress",
    "evaluate_stress_conditions",
    "list_environment_plants",
    "get_pest_guidelines",
    "recommend_pest_treatments",
    "get_pest_prevention",
    "recommend_pest_prevention",
    "get_pest_resistance",
    "list_pest_plants",
    "get_pest_thresholds",
    "assess_pest_pressure",
    "recommend_threshold_actions",
    "get_disease_guidelines",
    "recommend_disease_treatments",
    "get_disease_prevention",
    "recommend_disease_prevention",
    "get_disease_resistance",
    "list_disease_plants",
    "get_disease_thresholds",
    "assess_disease_pressure",
    "classify_disease_severity",
    "recommend_disease_threshold_actions",
    "estimate_disease_risk",
    "generate_disease_report",
    "generate_integrated_monitoring_schedule",
    "recommend_fertigation_schedule",
    "recommend_correction_schedule",
    "get_fertilizer_purity",
    "recommend_nutrient_mix_with_cost_breakdown",
    "generate_fertigation_plan",
    "calculate_mix_nutrients",
    "estimate_stage_cost",
    "estimate_cycle_cost",
    "optimize_fertigation_schedule",
    "generate_cycle_fertigation_plan",
    "generate_cycle_fertigation_plan_with_cost",
    "recommend_loss_compensated_mix",
    "generate_daily_uptake_plan",
    "recommend_stock_solution_injection",
    "recommend_rootzone_fertigation",
    "get_foliar_spray_volume",
    "estimate_spray_solution_volume",
    "calculate_deficiencies",
    "calculate_micro_deficiencies",
    "get_deficiency_treatment",
    "recommend_deficiency_treatments",
    "diagnose_deficiency_actions",
    "list_surplus_nutrients",
    "get_surplus_action",
    "recommend_surplus_actions",
    "list_interactions",
    "get_interaction_info",
    "get_max_ratio",
    "get_interaction_message",
    "check_imbalances",
    "get_balance_action",
    "recommend_balance_actions",
    "analyze_interactions",
    "list_nutrient_plants",
    "get_nutrient_weight",
    "score_nutrient_levels",
    "get_ph_adjusted_levels",
    "calculate_deficiencies_with_ph",
    "list_micro_plants",
    "get_micro_levels",
    "list_silicon_plants",
    "get_silicon_levels",
    "calculate_silicon_deficiencies",
    "calculate_silicon_surplus",
    "list_bio_plants",
    "get_recommended_inoculants",
    "list_companion_plants",
    "get_companion_info",
    "recommend_companions",
    "recommend_antagonists",
    "list_rotation_plants",
    "get_rotation_info",
    "recommended_rotation_years",
    "get_stage_info",
    "list_growth_stages",
    "days_until_next_stage",
    "list_task_plants",
    "get_stage_tasks",
    "generate_task_schedule",
    "build_stage_schedule",
    "estimate_rootzone_depth",
    "estimate_water_capacity",
    "get_soil_parameters",
    "get_infiltration_rate",
    "estimate_infiltration_time",
    "RootZone",
    "list_soil_plants",
    "get_soil_targets",
    "calculate_soil_deficiencies",
    "calculate_soil_surplus",
    "score_soil_nutrients",
    "recommend_irrigation_volume",
    "recommend_irrigation_interval",
    "list_irrigation_plants",
    "get_daily_irrigation_target",
    "generate_irrigation_schedule",
    "generate_irrigation_schedule_with_runtime",
    "summarize_irrigation_schedule",
    "generate_cycle_irrigation_plan",
    "HarvestRecord",
    "load_yield_history",
    "record_harvest",
    "get_total_yield",
    "get_total_nutrient_removal",
    "list_yield_plants",
    "get_estimated_yield",
    "estimate_remaining_yield",
    "list_budget_plants",
    "get_removal_rates",
    "estimate_total_removal",
    "estimate_required_nutrients",
    "estimate_fertilizer_requirements",
    "estimate_solution_volume",
    "generate_health_report",
    "list_water_analytes",
    "get_water_threshold",
    "interpret_water_profile",
    "list_ec_plants",
    "get_ec_range",
    "classify_ec_level",
    "recommend_ec_adjustment",
    "list_water_use_plants",
    "get_daily_water_use",
    "estimate_stage_total_use",
    "estimate_cycle_total_use",
    "list_ph_plants",
    "get_ph_range",
    "recommend_ph_adjustment",
    "estimate_ph_adjustment_volume",
    "list_spectrum_plants",
    "get_light_spectrum",
    "get_red_blue_ratio",
    "list_pruning_plants",
    "list_pruning_stages",
    "get_pruning_instructions",
    "calculate_gdd",
    "list_gdd_plants",
    "get_stage_gdd_requirement",
    "predict_stage_completion",
    "accumulate_gdd_series",
    "calculate_all_surplus",
    "calculate_micro_surplus",
    "analyze_nutrient_profile",
    "list_leaching_nutrients",
    "get_leaching_rate",
    "estimate_leaching_loss",
    "compensate_for_leaching",
    "list_volatilization_nutrients",
    "get_volatilization_rate",
    "estimate_volatilization_loss",
    "compensate_for_volatilization",
    "list_recovery_nutrients",
    "get_recovery_factor",
    "estimate_recovered_amounts",
    "adjust_for_recovery",
    "list_toxicity_plants",
    "get_toxicity_thresholds",
    "check_toxicities",
    "classify_nutrient_status",
    "get_guideline_summary",
    "get_withdrawal_days",
    "earliest_harvest_date",
    "adjust_harvest_date",
    "get_reentry_hours",
    "earliest_reentry_time",
    "calculate_reentry_window",
    "DailyReport",
    "load_profile",
    "TranspirationMetrics",
    "calculate_nue",
    "calculate_nue_for_nutrient",
    "STAGE_MULTIPLIERS",
    "get_stage_multiplier",
    "DEFAULT_ENV",
    "get_water_cost_rate",
    "estimate_water_cost",
]
