blueprint:
  name: Horticulture Assistant - Plant Monitor
  description: >
    Monitor a plant’s sensors (moisture, EC, etc.), notify user or trigger actions
    when thresholds are breached. Supports optional AI output, yield estimation,
    and auto-approve logic for irrigation/fertilization.

  domain: automation
  input:
    plant_name:
      name: Plant Name
      description: Name of the plant this automation applies to.
      selector:
        text:

    smoothed_moisture:
      name: Smoothed Moisture Sensor
      selector:
        entity:
          domain: sensor

    root_zone_depletion:
      name: Root Zone Depletion Sensor
      selector:
        entity:
          domain: sensor

    smoothed_ec:
      name: Smoothed EC Sensor
      selector:
        entity:
          domain: sensor

    field_capacity:
      name: Field Capacity Sensor
      selector:
        entity:
          domain: sensor

    wilting_point:
      name: Wilting Point Sensor
      selector:
        entity:
          domain: sensor

    daily_nitrogen:
      name: Daily Nitrogen Sensor
      selector:
        entity:
          domain: sensor

    ai_recommendation:
      name: AI Recommendation Sensor
      selector:
        entity:
          domain: sensor

    irrigation_switch:
      name: Optional Irrigation Switch
      default: null
      selector:
        entity:
          domain: switch

    notify_user:
      name: Notify When Action Suggested?
      default: true
      selector:
        boolean:

    auto_approve:
      name: Use Auto-Approve Mode
      default: false
      selector:
        boolean:

trigger:
  - platform: numeric_state
    entity_id: !input root_zone_depletion
    above: 0.35  # 35% depletion triggers irrigation logic

condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.auto_approve
        state: "on"
      - condition: template
        value_template: "{{ not (auto_approve | default(false)) }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ auto_approve | default(false) and irrigation_switch is not none }}
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input irrigation_switch
          - delay:
              minutes: 5
          - service: switch.turn_off
            target:
              entity_id: !input irrigation_switch

    default:
      - if:
          - condition: template
            value_template: "{{ notify_user }}"
        then:
          - service: notify.persistent_notification
            data:
              title: "Plant Action Needed"
              message: >
                {{ plant_name }} is showing water depletion of
                {{ states(root_zone_depletion) }}. Moisture at
                {{ states(smoothed_moisture) }}%. Recommendation: 
                {{ states(ai_recommendation) or 'Water now.' }}

mode: restart
