name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements_test.txt
      - name: Ruff
        run: >-
          ruff check
          custom_components/horticulture_assistant/__init__.py
          custom_components/horticulture_assistant/config_flow.py
          custom_components/horticulture_assistant/sensor.py
          custom_components/horticulture_assistant/storage.py
          custom_components/horticulture_assistant/coordinator_ai.py
          custom_components/horticulture_assistant/coordinator_local.py
          tests/test_config_flow.py
          tests/test_coordinator_ai.py
          tests/test_storage_migration.py
          tests/test_services.py
          tests/test_coordinator_local.py
          tests/test_integration.py
      - name: Mypy
        run: mypy . || true
      - name: Pytest
        run: pytest
