name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 8 * * 1'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: home-assistant/actions/hassfest@master

  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for --from-ref/--to-ref
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Upgrade pip, setuptools, and wheel
        run: python -m pip install --upgrade pip setuptools wheel
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements_test.txt ]; then pip install -r requirements_test.txt; fi
          pip install ruff mypy pytest pytest-asyncio pytest-homeassistant-custom-component pre-commit jsonschema
      - name: Validate plant profiles
        run: python scripts/validate_profiles.py
      - name: Run pre-commit (changed files or fallback all)
        run: |
          pre-commit run --from-ref origin/main --to-ref HEAD || pre-commit run --all-files
      - name: Type check (non-blocking)
        run: mypy --explicit-package-bases custom_components/horticulture_assistant || true
      - name: Run tests
        run: pytest -q
