name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Upgrade pip/setuptools/wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dev tools
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r requirements_test.txt
          python -m pip install hassfest==0.7.6 ruff==0.6.8 mypy==1.11.2

      - name: Pre-commit (format & JSON checks)
        run: |
          python -m pip install pre-commit==3.7.1
          pre-commit run --all-files

      - name: Hassfest (non-blocking)
        continue-on-error: true
        run: hassfest

      - name: Ruff (lint)
        run: ruff check .

      - name: Pytest
        run: pytest -q

      - name: Validate fertilizer data (if present)
        run: |
          if [ -f scripts/validate_profiles.py ]; then
            python scripts/validate_profiles.py
          fi
          if [ -f scripts/validate_fertilizers_v3e.py ]; then
            python scripts/validate_fertilizers_v3e.py
          fi
